# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The Happy Bug
tagline:          'The ramblings of a software engineer + web designer in the making.'
description:      'I do the same things that other people do but when I do those things, people say that the things I do, I do them awesome.'
url:              http://thehappybug.github.io
baseurl:          /

author:
  name:           'Happiest Bug'
  url:            http://thehappybug.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
