# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The Happy Bug
tagline:          'A happy bug is an awesome bug.'
description:      'The ramblings of a software engineer and web designer in the making.'
url:              http://thehappybug.github.io
baseurl:          /

author:
  name:           'Happiest Bug'
  url:            http://thehappybug.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
